### ISSUE TITLE
Ability to open a terminal in a separate buffer

### ISSUE THREAD

**Issue by niceloaf** [akinsho/nvim-toggleterm.lua#20]
Is there a way you could open the terminal buffer in a separate buffer instead of a split?

**Comment by akinsho** [comment]
@niceloaf do you mean a full window? since when the terminal is open it already creates a buffer. The buffer is just the file contents or in this case the shell. the window is what is what contains the content. In the case of toggle term, it creates a split window, so I'm guessing what youre asking is if it can be a full window not a split.

In which case basically no currently that isn't supported but someone could add this as new `direction` option maybe as both a tab and a window or just as a window to start. Shouldn't be too hard to do, not sure when I'll get to it myself, but happy to leave pointers if someone wants to look into this.

**Comment by akinsho** [comment]
@niceloaf this plugin now offers a new `direction` which is `window` which will allow for creating a full window terminal. Fixed by #21
