### ISSUE TITLE
Open mappings only in normal mode?

### ISSUE THREAD

**Issue by zetashift** [akinsho/nvim-toggleterm.lua#22]
Is there a way to toggle the terminal only when in normal mode, using the provided `open_mapping` settings? Or can this only be done using the manual way? I'm new to neovim (and lua), so apologies in advance if this is a dumb question.

This is what I'd like:

In normal mode \` will toggle a terminal and in insert I'd have it mapped to Ctrl + \` . 

PS:I tried a different mapping as an experimentation, but I couldn't get it to work. It was: `<leader> o t` and I used `[[<leader>ot]]` as the value of `open_mappings`. Am I formatting it wrong?

**Comment by akinsho** [comment]
@zetashift I think I understand what you want, in which case you can remove the insert mode mappings using `insert_mappings = false` and add an `inoremap` mapping to trigger toggle term like
`inoremap <c-b> <cmd>ToggleTerm`. Regarding the using a leader mapping that should work fine. Can you paste the out put of running `:verbose map <leader>ot`. The plugin basically passes the lhs you specify directly to `nvim_buf_set_keymap` so that should work. I haven't had any issues so far

**Comment by zetashift** [comment]
Hiya! Thanks `insert_mappings` was indeed what I was looking for. 

`:verbose map <leader>ot` gives me: `No mapping found`

My setup function being

```lua
require"toggleterm".setup{
  size = 20,
  open_mapping = [[<leader>ot]],
  shade_filetypes = {},
  shade_terminals = true,
  shading_factor = '1', -- the degree by which to darken to terminal colour, default: 1 for dark backgrounds, 3 for light
  start_in_insert = true,
  persist_size = true,
  direction = 'horizontal',
  insert_mappings = false,
}
```

**Comment by akinsho** [comment]
Hmm can you try another mapping maybe using the key directly instead of `<leader>` or just another key just to see what it does

**Comment by zetashift** [comment]
Well currently I use ` (backtick) key and that works fine.

**Comment by akinsho** [comment]
@zetashift I've just tried it using your leader mapping and that works fine for me. Could anything else be conflicting this or is `<leader>` set before this function is run? Does it work if you use `\ot` or `,ot` or whatever your leader value is

**Comment by zetashift** [comment]
I was setting my <leader> wrong indeed, thank you for your help and this great plugin!
