### ISSUE TITLE
Error on Terminal Toggle

### ISSUE THREAD

**Issue by bscuron19** [akinsho/nvim-toggleterm.lua#24]
I keep getting this error when I toggle the terminal:

<img width="1107" alt="Screen Shot 2021-04-16 at 9 13 59 AM" src="https://user-images.githubusercontent.com/29784485/115029548-15061280-9e94-11eb-85c1-0e045707c96c.png">

Here is my mapping in my init.vim:

<img width="356" alt="Screen Shot 2021-04-16 at 9 14 39 AM" src="https://user-images.githubusercontent.com/29784485/115029633-2cdd9680-9e94-11eb-8fcd-f8124af2a36a.png">

Please let me know if I am doing something wrong. Thanks!

**Comment by akinsho** [comment]
@bscuron19 thanks for trying out the plugin. There are a few bits missing from this report I  need in order to help you out. The screenshot you show only includes part of the message so I can't exactly seen what's going on. Also are you on `nvim nightly`? what version of this plugin are you using? latest commit?

Regarding you mapping tbh you should really need to map togglerm like that since you won't be able to open specific terminals using a count. This plugin offers an `open_mapping` in the config which is what you should use then you can do 
`open_mapping = ",,"` and to open terminal one `1,,` or terminal 2 `2,,`. Anyway doing toggle term like you've done shouldn't be an issue. I just tried it locally on the latest commit and it works fine

**Comment by bscuron19** [comment]
Nvim version:
NVIM v0.5.0-dev+0ab88c2ea

I am using Vim-Plug as my plugin manager and I ran :PlugUpdate so I am on the latest commit

I will look into the open mapping that you suggested

To get the full error message, do you have a recommendation on how to do that? When I run the ToggleTerm command that is the only message I see.

**Comment by bscuron19** [comment]
I just tried using the open mapping like you suggested and everything now works perfectly! Thanks for your help

**Comment by akinsho** [comment]
Yeah the open mapping is required if not the plugin will error. I'll add a more clear error message for the future 👍🏿 otherwise will close this if it now works for you?

**Comment by bscuron19** [comment]
Yes this works thanks!
