### ISSUE TITLE
why i can't work in the same termninal

### ISSUE THREAD

**Issue by likelxl** [akinsho/nvim-toggleterm.lua#25]
i use the latest neovim and plugin,my config is below:
```
require"toggleterm".setup{
  size = 20,
  open_mapping = [[<c-A-\>]],
  shade_filetypes = {},
  shade_terminals = true,
  shading_factor = '<number>',
  start_in_insert = true,
  persist_size = true,
  direction = 'horizontal',
}
```
before i can use number and this keymap([c-a-\]) use the  same serial number term to run diffrent command in their respective term,but now it can't, every time it open a new term with clear info, then the command I ran is missing, it can't be reduced.
What can I do to achieve the previous effect?

**Comment by akinsho** [comment]
@likelxl I'm not sure I understand entirely what you mean. I've just tested my mapping and everything still works. The open mapping you are using doesn't look like a valid vim mapping I don't think you can bind those keys like that. I think what that mapping should look like is `<c-a>\` maybe. But in any case I need more information about what *exactly* you are doing step by step that isn't working

**Comment by likelxl** [comment]
![录屏_deepin-terminal_20210417091202](https://user-images.githubusercontent.com/12811070/115097549-8f4e9980-9f5d-11eb-830d-179005d2455c.gif)
the command I ran is missing, because it open a new term

**Comment by akinsho** [comment]
@likelxl I was able to reproduce your issue and it seems to happen if you don't set `hidden` in your neovim config. I just assumed that everyone using vim has this setting on tbh. Not sure why the refactor has exposed this problem. Probably because it now uses nvim apis to close the window. Can add
`set hidden` or `vim.o.hidden = true` (if using `lua` to your config and see if fixes this for you)

**Comment by likelxl** [comment]
ok, set hidden, solve my problem
