### ISSUE TITLE
Background color issue

### ISSUE THREAD

**Issue by Johan-Palacios** [akinsho/nvim-toggleterm.lua#59]
When i open Toggle terminal, I have this issue

![image](https://user-images.githubusercontent.com/77251405/125727544-9a241343-08c3-4175-9d25-d0f6d06a7fb8.png)

Can you give a solution for this?

**Comment by akinsho** [comment]
Hi @Johan-Palacios,

Can you clarify what the problem is specifically? Is it that your terminal is dark? This plugin doesn't apply any highlighting to floats. In all likelihood, your colorscheme includes some terminal colours and is what is making your terminal that colour. Can you try with a minimal init.vim i.e. remove the colorscheme and see if it still behaves this way.

**Comment by Johan-Palacios** [comment]
My terminal has one dark coloscheme, and I disabled the colorshceme in my init.vim and I have the same issue

![image](https://user-images.githubusercontent.com/77251405/125849050-3b13ced2-3f82-4e6f-a36a-cc8616a766aa.png)

**Comment by akinsho** [comment]
@Johan-Palacios can you run a few tests for me. With the float window open can you run `:verbose set winhiglight?` and paste the result here. Can you also check what the value of `NormalFloat` is using `:highlight NormalFloat` it could be that your config or a plugin or something sets the normal float to that dark colour, which is the highlight group this plugin uses.

**Comment by akinsho** [comment]
@Johan-Palacios any news? I can't reproduce this in a minimal configuration on my end. This is what a completely minimal nvim with *only* toggleterm using a floating window looks like.

<img width="1253" alt="Screen Shot 2021-07-21 at 14 32 41" src="https://user-images.githubusercontent.com/22454918/126497173-0c5f7fcf-5dbd-49e9-af95-67dbadd2ea78.png">

There is no black background it seems *very likely* that this issue relates to a colour scheme or config issue since it's not reproducible on a minimal config.

**Comment by Johan-Palacios** [comment]
I tried a minimal config and I have the same issue, for this reason now I use the terminal in vertical. I suppose that is a conflict with WSL

**Comment by akinsho** [comment]
@Johan-Palacios how did you run the minimal config? if you use something like `packer` start plugins are loaded automatically? so it would still load any of your start plugins. You have to run `nvim -u <path/to/minimal> --noplugin` to ensure none of the start plugins are loaded

**Comment by Johan-Palacios** [comment]
A ok I will try this

**Comment by akinsho** [comment]
@Johan-Palacios up to you in the end 🤷🏿 I doubt this is related to WSL especially since you tried other plugins and that worked. If anyone else with this issue wants to help me debug it by trying to isolate the problem, please try the minimal config above and see if that helps if not we can try some other stuff to debug it.

**Comment by Johan-Palacios** [comment]
![image](https://user-images.githubusercontent.com/77251405/126712324-9ad5ddf9-1981-43c3-be32-510e08f9b6d0.png)

![image](https://user-images.githubusercontent.com/77251405/126712349-bce14e26-7edd-4cb6-a915-a60d75459b70.png)

Look this is very weird, and i discovered that black color in the bagraund is caused for a effect of 
blurred, that have this plugin when this stay in float mode

**Comment by akinsho** [comment]
@Johan-Palacios can you try setting 
```lua
float_opts = {
    winblend = 0, -- this value here might be the problem
    highlights = {
      border = "Normal",
      background = "Normal", -- if not try setting this to Pmenu or String and see what happens
    }
```

**Comment by Johan-Palacios** [comment]
![image](https://user-images.githubusercontent.com/77251405/126713481-54278690-a24a-4aeb-866a-f30baf06700a.png)


JAJAJA sorry bro it works now xd

**Comment by Johan-Palacios** [comment]
and i have a question, you know how i can open the float or vertical mode of this plugins with diferents commands?

**Comment by akinsho** [comment]
> JAJAJA sorry bro it works now xd

Did any specific thing make it work? Or did it just start working.

@Johan-Palacios the README covers all the different ways to use the plugin, you can also just set your preference in the plugin's config.

**Comment by Johan-Palacios** [comment]
> > JAJAJA lo siento bro funciona ahora xd
> 
> ¿Alguna cosa específica hizo que funcionara? O simplemente empezó a funcionar.
> 
> @Johan-Palacios el archivo README cubre todas las diferentes formas de usar el complemento, también puede establecer su preferencia en la configuración del complemento.

First i Update the plugin, later I deleted line of code that i have, later of that i only change the values of the float_opt and it works, really weird bro

**Comment by Johan-Palacios** [comment]
> and i have a question, you know how i can open the float or vertical mode of this plugins with diferents commands?

You know something for this?

**Comment by akinsho** [comment]
@Johan-Palacios, all the instructions on how to use this plugin are in the README please take a look there's a lot to go through and I unfortunately am pressed for time. You need to add the `direction` you want in the `setup` config or in the command like `ToggleTerm direction=vertical` etc. (please read the docs 🙏🏿 )

**Comment by Johan-Palacios** [comment]
Thank you bro, yeah I'm a noob in this and I need to read this docs, thanks for your help 👍
