### ISSUE TITLE
Failed to close window

### ISSUE THREAD

**Issue by ffuszthaler** [akinsho/nvim-toggleterm.lua#60]
**When I toggle the terminal I get this error message:**

_Failed to close window: win id - <number> does not exist_

**my config:**

require("toggleterm").setup {
  size = 20,
  open_mapping = [[<C-y>]],
  hide_numbers = true,
  shade_filetypes = {},
  shade_terminals = true,
  shading_factor = 1,
  start_in_insert = true,
  insert_mappings = true,
  persist_size = true,
  direction = "horizontal",
  close_on_exit = true,
  shell = vim.o.shell,
  float_opts = {
    border = "single",
    winblend = 3,
    highlights = {
      border = "Normal",
      background = "Normal",
    },
  },
}

**Comment by akinsho** [comment]
Hi @ffuszthaler can you please provide a minimal init.vim or lua that reproduces this issue, based on the information you shared I will not be able to solve your issue.

Just to clarify have you got `hidden` set in your config? this is a requirement and is detailed in the README.

**Comment by ffuszthaler** [comment]
I added vim.o.hidden = true and now it appears to work, sorry I didn't see it

**Comment by Shatur** [comment]
@akinsho, I have the same issue when I using `:bdelete!`.
I have a plugin that switches sessions and it closes all buffers. So after every session switch I see this error. Is it possible to suppress this error message somehow?

**Comment by akinsho** [comment]
@Shatur are you using `hidden` or not? I won't suppress the error since it's actually a warning flag that something is going wrong, it means the plugin still has a reference to a buffer that no longer exists. Which shouldn't happen since there is an autocommand to listen for when a terminal closes and to tidy up the internal state of the plugin.

It might be that *if* you already have hidden set that that the autocommand isn't being triggered because the command is being executed with noautocmd or something. If you don't have hidden set then this error is unavoidable the plugin requires that setting otherwise it cannot background terminals

**Comment by Shatur** [comment]
@akinsho, yes, `:set hidden?` prints `hidden`. But I have this error.
So `:bdelete!` works for you without any errors?

**Comment by akinsho** [comment]
@Shatur sorry I wasn't entirely clear exactly what the issue you were reporting was and if it was related to this original issue or a session plugin or something. Just tried a naked `bdelete` and that does cause the error. Hadn't really anticipated people deleting the buffer, I don't so 🤷🏿‍♂️. Bdelete removes the window before the terminal is closed, so when the terminal is shutdown the containing window is already gone, which is not expected. I'll have a look when I get some time.

**Comment by Shatur** [comment]
@akinsho, yes, sorry, it looks like my problem is not related to this issue. I just was not sure :)
