### ISSUE TITLE
Sending current line number to terminal?

### ISSUE THREAD

**Issue by jamesgecko** [akinsho/nvim-toggleterm.lua#62]
Is there a way to send the line number with `TermExec`? I know it's available to vim via `line('.')`, but that doesn't appear to be one of the things that the `expand` command expands.

Context: I'm trying to use the `:TermExec` command to execute ruby specs. To run all the specs in a file, I have this key binding:

```lua
vim.api.nvim_set_keymap('n', '<Leader>q', "<cmd>1TermExec cmd='bundle exec rspec %'<CR>", {})
```

That works great for executing entire files of specs. But Rspec has a feature that allows executing only the spec on a single line. To do this, I can append the line to the end of the filename, like so: `rspec my_spec.rb:23`. Based on the expand documentation, I thought that the following might work, but I guess my spec buffers aren't sourced script files: nvim says `no line number to use for "<sflnum>"`.
```lua
vim.api.nvim_set_keymap('n', '<Leader>q', "<cmd>1TermExec cmd='bundle exec rspec %:<sflnum>'<CR>", {})
```

**Comment by akinsho** [comment]
@jamesgecko I haven't really had this use case so tbh I'm not really sure, I guess you could create a function that generates the command instead of mapping to the string directly e.g.

```lua
function my_line_test()
  local lnum = vim.fn.line('.')
  vim.cmd(string.format("1TermExec cmd='bundle exec rspec %%:%d", lnum))
end

vim.api.nvim_set_keymap("n", "<leader>q", "<cmd>lua v:lua.my_line_test()<CR>)
```
you could also do something like that with the terminal api, but it's roughly equivalent.

**Comment by akinsho** [comment]
@jamesgecko came back to this after a day or so and realised you could probably use the lua api directly for this i.e. 
```lua
require('toggleterm').exec_command(1, ('bundle exec rspec %%:%d'):format(lnum)
```

**Comment by jamesgecko** [comment]
For some reason I couldn't get NeoVim to see the function in my init.lua. Here's what I ended up with:

**~/.config/nvim/lua/tools.lua**
```lua
local M = {}
function M.rspec_test_line()
  local path = vim.fn.expand('%')
  local lnum = vim.fn.line('.')
  return require('toggleterm').exec(('env SIMPLECOV=no bundle exec rspec %s:%d'):format(path, lnum), 1)
end
return M
```

**In ~/.config/nvim/init.lua**
```lua
map('n', '<Leader>w', "<cmd>lua require('tools').rspec_test_line()<CR>", {})
```

Thanks for the help!

**Comment by will** [comment]
This is cool. Is there an easy way to get this to also open the terminal if it's closed (but not toggle, keep it open if it happens to already be open). I'm new to all this lua vim stuff, so I've been trying to peek though the code to figure it out, but no luck so far.

**Comment by akinsho** [comment]
Hmm, not entirely sure if I follow, but `TermExec` and the underlying `exec` function will open a terminal if not opened or just send to that terminal if it is already open.

**Comment by will** [comment]
Maybe it's something lunarvim is doing ( https://github.com/ChristianChiarulli/LunarVim/blob/95aa1ea8c6b8dc31bae26fe1d433e83f57dd4201/lua/core/terminal.lua#L2 ) but when I run this, it does run the specs in the background but the the terminal stays hidden until I hit ctrl-t (they remapped it from your default). Once I do hit that the terminal will appear and the test output will be in there. 

I was hoping to make a key mapping that ran the test, and then showed the terminal in one step, vs the two it is for me now. Then again I might be using the whole thing wrong since I'm just blindly using this lunarvim setup

**Comment by akinsho** [comment]
Ah, it's probably because the whole float functionality only got added a few months ago. Seems term exec doesn't open a float like it does for splits since it doesn't really seem to take the direction into consideration, maybe. Anyway, feel free to open a new issue. I'm probably not going to handle it soon, nvim plugins are taking waaaay too much of my free time atm.

**Comment by will** [comment]
> nvim plugins are taking waaaay too much of my free time atm. 

I hear you. Even just playing around with all the new nvim stuff has been taking up all of mine since I wasn't paying attention to any of the nightly stuff pre 0.5 🤣
