### ISSUE TITLE
Input lag when navigating with j/k in file-managers

### ISSUE THREAD

**Issue by kylo252** [akinsho/nvim-toggleterm.lua#63]
# Problem description

There's a significant delay when navigating with j/k compared to using arrow-keys.

### Demo

![F99VLliCTe](https://user-images.githubusercontent.com/59826753/126135758-67cd69d4-cad5-4ab3-81bd-a09b7741c150.gif)

**Comment by akinsho** [comment]
Hi @kylo252 do you have any mappings for `j` or `k` in that buffer? you can check by going into normal mode and checking `verbose tmap j` and k. A common requirement for floating buffers using terminal programs is that you have to unmap some of your vim mappings since they cause you to have to wait for `timeoutlen` before executing. I can't/won't automatically remove them since I don't know what peoples mappings are or what their preferences might be.

**Comment by kylo252** [comment]
> Hi @kylo252 do you have any mappings for `j` or `k` in that buffer? you can check by going into normal mode and checking `verbose tmap j` 

Thanks for getting back me so fast on this. It turns out that I have somehow copied the mapping of `jk`-> `<Esc>` to terminal mode as well, I have no idea why I had it there.. 🤦 

Feel free to close the issue if this is working as intended.

**Comment by akinsho** [comment]
@kylo252 no worries it's a common issue, I did consider automatically removing those mapping but they are common but not 100% predictable and personally I'd rather stay out of the business of messing with user mappings when I don't know they preferences or use cases. I personally use this
```lua
        local float_handler = function(term)
          vim.cmd 'startinsert!'
          if vim.fn.mapcheck('jk', 't') ~= '' then
            vim.api.nvim_buf_del_keymap(term.bufnr, 't', 'jk')
            vim.api.nvim_buf_del_keymap(term.bufnr, 't', '<esc>')
          end
        end

```
I use that as my on open mapping to remove the mapping for my float terms

**Comment by ryuheechul** [comment]
I first encountered the issue when I started using https://github.com/voldikss/vim-floaterm.

I thought it could be a performance issue with `vim-floaterm` (or neovim) and now I know it is not (from those) and it's because of `jk` mapping (and it was mapped for all terminal not just for `toggleterm` as I copied and pasted the configuration from the readme).

I understand this is a tricky to figure out how to improve in terms of the feature within this plugin as the thread here explained.

However maybe mentioning this issue in the config example (in the readme) could help people to quickly understand what's happening in their embeded terminal.

For example,
```diff
  function _G.set_terminal_keymaps()
    local opts = {buffer = 0}
    vim.keymap.set('t', '<esc>', [[<C-\><C-n>]], opts)
+   -- this might cause the long pressing of `j` to be not responsive until release
    vim.keymap.set('t', 'jk', [[<C-\><C-n>]], opts)
    vim.keymap.set('t', '<C-h>', [[<Cmd>wincmd h<CR>]], opts)
    vim.keymap.set('t', '<C-j>', [[<Cmd>wincmd j<CR>]], opts)
    vim.keymap.set('t', '<C-k>', [[<Cmd>wincmd k<CR>]], opts)
    vim.keymap.set('t', '<C-l>', [[<Cmd>wincmd l<CR>]], opts)
  end

  -- if you only want these mappings for toggle term use term://*toggleterm#* instead
  vim.cmd('autocmd! TermOpen term://* lua set_terminal_keymaps()')
```

I also attaching what I did in this situation just for the reference, https://github.com/ryuheechul/dotfiles/commit/2c4e7e1786c301f2f33da9c9e75ec2c2b6cb52fa.
