### ISSUE TITLE
toggle back to nvim

### ISSUE THREAD

**Issue by menash134** [akinsho/nvim-toggleterm.lua#75]
How to toggle back to the neovim editor from the float/vertical terminal. At the moment, I tried ctrl+w+ctrl+w, but it is not working? Any solutions?

**Comment by vuki656** [comment]
Since I assume its a buffer, try `:q`

**Comment by akinsho** [comment]
@menash134, you press the `toggle` mapping that you set in your config for this plugin. The same mapping that opens the terminal, closes it.

**Comment by alextricity25** [comment]
Is it possible to leave the terminal open, and switch focus to back to vim while the terminal is still open? I believe that's what OP is referring to.

**Comment by alextricity25** [comment]
> Since I assume its a buffer, try `:q`

The terminal catches every key stroke, so I literally end up typing `:q` on the command prompt.

**Comment by alextricity25** [comment]
After some quick reading of the `nvim_terminal_emulator` docs, found out that all keys execpt <C-\><C-N> are sent to the underlying program. Use <C-\><C-N> to return to normal mode, then you can use the normal <C-w> commands to switch between windows. 

https://neovim.io/doc/user/nvim_terminal_emulator.html

![image](https://user-images.githubusercontent.com/4964964/127791837-e704082f-ead5-47e5-a770-0148ebbb33c5.png)

**Comment by akinsho** [comment]
I can't build these into they plugin since it's really a matter personal preference how/if to map window movement and inevitably some people will complain about the keys or just adding them at all.

I'll add an example to the README though so people can add these mappings If they want

**Comment by menash134** [comment]
Thanks @alextricity25 for understanding the question and explaining it. Thanks @akinsho for the solution. Iam trying to learn about this tnoremap. I hope I can figure out from your dotfiles. I think basic setting/mapping is necessary to be builtin the plugin to be there for nvim or atleast in your toggleterm git homepage.

**Comment by akinsho** [comment]
@menash134 sorry I don't follow exactly.

Tbh I wouldn't use my dotfiles as I'm not going for a simple solution there. I added a section to the README that shows you how to add the required mappings in vanilla nvim 0.5 so you can just copy and paste those. I don't think as I mentioned that this can/should be builtin since it goes beyond the scope of this plugin IMO to start messing with window navigation especially since it's not clear what and how people would like that to be mapped. I'd much rather avoid a bunch of future issues complaining about stepping on people's mappings or other stuff like that.

**Comment by menash134** [comment]
Thank you akinsho. Read me is perfect.
