### ISSUE TITLE
Multiple terminals

### ISSUE THREAD

**Issue by unnsteinngardars** [akinsho/nvim-toggleterm.lua#77]
Hello, I have been trying without success to manage mapping keys to toggling multiple terminals. I can manage to open the terminal by using the open_mapping keymap but when I am already in an open terminal and in terminal mode, I cannot do 2<C-\> to open another terminal because it just writes the letter 2 into the terminal and then just closes it.

**Comment by akinsho** [comment]
@unnsteinngardars the count for the open mapping can't be passed on whilst you are still in terminal mode after opening a terminal. Terminal mode is similar to insert mode so if you write two it will enter 2 rather than count it as part of the mapping. There's really nothing I can do here since this is just nvim behaviour. The best way to handle this is to map an escape sequence whilst in the terminal and escape to normal mode and then hit your mapping.

You can use the `<Esc>` mapping I recommend in the README for this purpose
https://github.com/akinsho/nvim-toggleterm.lua#terminal-window-mappings

**Comment by unnsteinngardars** [comment]
Thanks for your answer, it is correct that it is normal behavior but your readme suggested that the **key** to use, which I suspect is the **open_mapping** key, should work in normal, insert and terminal mode. If that is not correct then what do you mean with the following paragraph?


"Setting the key to use for toggling the terminal(s) will setup mappings for insert, normal and terminal modes If you prefix the mapping with a number that particular terminal will be opened."

**Comment by akinsho** [comment]
@unnsteinngardars the README has changed a lot over time and there are undoubtedly some inaccuracies in places as I maintain this and a few other plugins. The paragraph you refer to is meant to explain that use can use the open mapping in terminal mode and the subsequent sentence although the full stop is missing is to clarify that the open mapping takes a count, this should have a caveat explaining that terminal mode is an exception to this.

If you'd be willing to open a PR that would be helpful.

**Comment by unnsteinngardars** [comment]
I will take a look at the code and see if I can figure out how to add this and then create a PR. 

Thanks for the clarification

**Comment by akinsho** [comment]
@unnsteinngardars sorry just to clarify this doesn't require a code change, you just need to update the docs.

As for how to open multiple terminals in the GIF you need to add the `<esc>` that I linked to from the README to your config so that you can escape terminal mode and go into normal mode using a mapping like `jk` then you can press the open mapping with a count. Please read the link to the README with the mappings I mentioned that should help.

**Comment by akinsho** [comment]
@unnsteinngardars to make a PR you have to *fork* the repository then make a PR off of a branch you create. The easiest way to do this for something like the README is by clicking the edit icon on github
Have a look at [this guide](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request)

**Comment by akinsho** [comment]
fixed by #79
