### ISSUE TITLE
shade_terminal isn't useful for light themes

### ISSUE THREAD

**Issue by urandom** [akinsho/nvim-toggleterm.lua#8]
It produces a very low-contrast terminal that's very hard to see. A better approach might be to darken the terminal if the user uses a light theme instead.

**Comment by akinsho** [comment]
@urandom thanks for raising this 👍🏿 can you share a screen shot +/- the color scheme name since I'm not sure what it looks like, light themes is a bit of a best effort since I never really use one other than the one that is part of `vim-one` once in a blue moon and that works fine with toggle term so that's what I based the light behaviour off of

**Comment by urandom** [comment]
@akinsho 
Here's a link to a screenshot
https://imgur.com/cmyC84z

As you can see, the contrast is less than ideal. I assume the shade function reduces the lightness of the colors, which might be a wrong choice for light backgrounds, since the fonts are darker. A better result might be to increase the lightness instead.

I'm currently using the edge color scheme.

**Comment by akinsho** [comment]
Hmm I'll have a play around to see what might work, I think increasing the lightness might amp up the brightness in an undesirable way. It might better instead to darken things even further for bright colorschemes so the contrast is greater

**Comment by akinsho** [comment]
Going to close this now @urandom if the solution is workable for you
