### ISSUE TITLE
Cursor look in insert mode

### ISSUE THREAD

**Issue by andreicorpo** [akinsho/nvim-toggleterm.lua#83]
The cursor still looks like a block when in the terminal in insert mode and it can be a bit confusing.

Is this intended or is there a way to have the default behaviour?

**Comment by akinsho** [comment]
@andreicorpo this plugin doesn't really have any relationship with your cursor at all tbh the cursor shape in neovim is controlled by the `guicursor` option which is a global setting that the user can set to change how their cursor behaves. I won't be messing with that in this plugin since a user can already decide how they want it to behave by setting it

**Comment by andreicorpo** [comment]
Thank you for you quick answer! But I have problems with setting the cursor via `guicursor`, I can't find a option to set the terminal cursor with it.

**Comment by akinsho** [comment]
@andreicorpo tbh I don't know how/if you can set the terminal mode cursor, but I guess in general I don't really think this plugin should mess with a user's cursor. I personally don't think that is part of the functionality this plugin should provide. I think the best way to achieve this is to set an autocommand on `TermOpen` and see if the `guicursor` can be changed on term enter and termleave, but I won't add that here since it will open a can of worms and I think a lot of people (myself included) won't want this plugin to mess with their cursor.

**Comment by andreicorpo** [comment]
Sure, I totally agree. I was just curious if it was possible, not necessarily via the plugin. Thank you so much for your answers! I'll close the issue now.

**Comment by xzbdmw** [comment]
changing terminal cursor shape  is still impossible in neovim
